"""Add session_id column to chat_history table

Revision ID: a1b2c3d4e5f6
Revises: c6c994114e39
Create Date: 2025-01-10 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "c6c994114e39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Table already exists, just add the session_id column
    op.add_column(
        "chat_history",
        sa.Column(
            "session_id",
            sa.String(length=255),
            nullable=True,
            comment="Session ID to group related messages",
        ),
    )
    op.create_index("idx_session_id", "chat_history", ["session_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_session_id", table_name="chat_history")
    op.drop_column("chat_history", "session_id")
    # ### end Alembic commands ###
