"""Add profile_picture column to users table"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6c994114e39"
down_revision: Union[str, None] = "6280f291867c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "profile_picture",
            sa.String(length=512),
            nullable=True,
            comment="URL of the user's profile picture (if uploaded)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_picture")
    # ### end Alembic commands ###
